#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import math
import re

crap = {
    "π": math.pi,
    "ℤ": "int",
    "∀": "for",
    "∈": "in",
    "λ": "lambda",
}
patt = '|'.join(k for k in crap)

fd = open(sys.argv[1], 'r')
buff = re.sub(patt, lambda matched: str(crap[matched.group()]), fd.read())

exec(buff)
