#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import math
import re

crap = {
    "π": math.pi,
    "ℤ": "int",
    "∀": "for",
    "∈": "in",
    "λ": "lambda",
    r"(\"{1,3}|\'{1,3})([^\1\\]*?(\\.[^\1\\]*?)*?)\1": None,
}
patt = '|'.join(k for k in crap)

def repl(matched):
    if matched.group()[0] in ('"', "'"):
        return matched.group()
    else:
        return str(crap[matched.group()])

fd = open(sys.argv[1], 'r')
buff = re.sub(patt, repl, fd.read())

exec(buff)
